#!/bin/bash

BLUE='\033[0;36m'
NC='\033[0m' # No Color

if [[ $# == 0 ]] then
    echo -e "Usage: cwreport [${BLUE}Project${NC}]\n"
    echo -e "Avaliable projects:\n"
    echo -e "${BLUE}meshulam"
    echo -e "${BLUE}mcdonalds"
    exit 1
fi

case "$1" in
    meshulam)
        echo "Python output:\n\n"
        python "/home/angel/PyCharm/meshulam report/Main.py"
        ;;
    mcdonalds)
        echo "Python output:\n\n"
        python "/home/angel/PyCharm/mcdonalds report/Main.py"
        ;;
    --help)
        echo -e "Usage: cwreport [${BLUE}Project${NC}]\n"
        echo -e "Avaliable projects:\n"
        echo -e "${BLUE}meshulam"
        echo -e "${BLUE}mcdonalds"
        ;;
    *)
        echo "No such command: ${1}. Please use --help"
        exit 1
esac

exit 0