#!/bin/bash

BLUE='\033[0;36m'
NC='\033[0m' # No Color

if [[ $1 == 0 ]] then
    echo -e "Usage: cwreport [${BLUE}Project${NC}]\n"
    echo -e "Avaliable projects:\n"
    echo -e "${BLUE}meshulam"
    echo -e "${BLUE}mcdonalds"
fi

case "$1" in
    meshulam)
        echo "Python output:\n\n"
        python "/home/angel/PyCharm/meshulam report/Main.py"
