#!/bin/bash

# Define color codes
BLUE='\033[0;36m'
NC='\033[0m' # No Color

# Check if any argument is provided
if [[$# == 0]]; then
    echo -e "Usage: iam [${BLUE}Command${NC}]\n\nAvaliable commands:\n\n${BLUE}scan\t\t${NC}Scan iam users and opens a list of them\n${BLUE}list\t\t${NC}Open the iam users list"
    exit 1
fi

case "$1" in
    scan)
        python "/home/angel/PyCharm/iam user scanner/main.py"
        code "/home/angel/PyCharm/iam user scanner/iam_users_list.txt"
        ;;
    list)
        code "/home/angel/PyCharm/iam user scanner/iam_users_list.txt"
        ;;
    --help)
        echo -e "Usage: iam [${BLUE}Command${NC}]\n\nAvaliable commands:\n\n${BLUE}scan\t\t${NC}Scan iam users and opens a list of them\n${BLUE}list\t\t${NC}Open the iam users list"
        ;;
    *)
        echo -e "No such command: ${1}. Please use --help"
        exit 1
python "/home/angel/PyCharm/iam user scanner/main.py"
code "/home/angel/PyCharm/iam user scanner/iam_users_list.txt"


